#!/bin/zsh

#HELP
help="Usage: $0 [path to your dotfiles]\nBacks up .zshrc and .vimrc and creates symbolic links to these files in ~\n--no-backup, don't backup .zshrc and .vimrc\nThe default location is ~/dontfiles"

#Default Values
backup=true
dontfiles=~/dontfiles

#Parse input
if [[ $# -gt 2 ]] then; #too many arguments
    echo "Usage: $0 [OPTIONS] [path to your dotfiles]"
elif [[ $# -eq 1 ]] then; #one argument
    if [[ $1 -eq "-h" -o $1 -eq "--help" ]] then; #print help
        echo $help
    else #set dontfiles path
        dontfiles="$1"
    fi
elif [[ $# -eq 2 ]] then; #two arguments
    if [[ $1 -neq "--no-backup" ]] then;
        echo $help
    else
        backup=false
    fi
fi


#remove symlinks form path
dontfiles=$(realpath -e "$1")

#files to replace
files=(".zshrc" ".vimrc")

#replace each file
for rc in "${array[@]}"; do
    if [[ -e $dontfiles/$rc ]]; then
        if $backup then
            ln -sb --suffix=.pre-lnkrc $dontfiles/$rc ~/$rc
        else
            ln -sf $dontfiles/$rc ~/$rc
        fi
    else
        echo "$rc doesn't exist in $dontfiles"
    fi
done
